spring.application.name=SpringAIDemoProj
# =========================
# DATABASE CONFIG
# =========================
spring.datasource.url=jdbc:postgresql://localhost:5432/springai_db
spring.datasource.username=dharanish
spring.datasource.password=1234

spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# JPA CONFIG
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =========================
# OLLAMA CONFIG
# =========================
spring.ai.ollama.base-url=http://localhost:11434

spring.ai.ollama.chat.model=llama3.2
spring.ai.ollama.embedding.model=nomic-embed-text